# -*- coding: utf-8 -*-
"""cv-finetune-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqRVA3SvlKH8MQjXahJ-leRQ0MEqpUcL
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.environ['KAGGLE_USERNAME'] = 'fauziaannisa'  # ganti sama username kaggle kamu
os.environ['KAGGLE_KEY'] = 'KGAT_e45808d8fa32ce96a4f7954dbae9a456' # token kamu

!pip install kaggle -q
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q chest-xray-pneumonia.zip -d /content/chest_xray
!ls /content/chest_xray

import os
print("Isi /content/chest_xray:")
print(os.listdir('/content/chest_xray'))

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

# CATAT: TAMBAH /chest_xray LAGI
train_data = train_datagen.flow_from_directory(
    '/content/chest_xray/chest_xray/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

val_data = train_datagen.flow_from_directory(
    '/content/chest_xray/chest_xray/val',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

test_data = train_datagen.flow_from_directory(
    '/content/chest_xray/chest_xray/test',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

print("Classes:", train_data.class_indices)
print("Total train images:", train_data.samples)

base_model = tf.keras.applications.ResNet50(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print("Training V1...")
history1 = model.fit(train_data, validation_data=val_data, epochs=5)

base_model.trainable = True # buka layer

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("Training V2...")
history2 = model.fit(train_data, validation_data=val_data, epochs=5)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(history1.history['accuracy'], label='V1 Train')
plt.plot(history1.history['val_accuracy'], label='V1 Val')
plt.plot(history2.history['accuracy'], label='V2 Train')
plt.plot(history2.history['val_accuracy'], label='V2 Val')
plt.legend()
plt.title('Iterative Fine-Tuning Accuracy')
plt.show()